- name: Print Parameter Store
  hosts: localhost
  tasks:
    - name: Create Value
      community.aws.aws_ssm_parameter_store:
        name: "param.dev.catalogue.MONGO"
        value: "false"
        region: "us-east-1"
      loop:
          - {name: "param.dev.catalogue.MONGO", value: "true"}
          - {name: "param.dev.user.MONGO", value: "true"}



