- name: Print Parameter Store
  hosts: localhost
  tasks:
    - name: Create Value
      community.aws.aws_ssm_parameter_store:
        name: "{{item.name}}"
        value: "{{item.value}}"
        region: "us-east-1"
      loop:
          - {name: "param.dev.catalogue.MONGO", value: "true"}
          - {name: "param.dev.catalogue.MONGO_ENDPOINT", value: "http://dev-mongodb.bhakti-19.net"}
          - {name: "param.dev.catalogue.MONGO_URL", value: "mongodb://dev-mongodb.bhakti-19.net:27017/catalogue"}
          - {name: "param.dev.user.MONGO", value: "true"}
          - {name: "param.dev.frontend.CATALOGUE_URL", value: "http://dev-catalogue.bhakti-19.net:8080/"}
          - {name: "param.dev.frontend.USER_URL", value: "http://dev-user.bhakti-19.net:8080/"}
          - {name: "param.dev.frontend.CART_URL", value: "http://dev-cart.bhakti-19.net:8080/"}
          - {name: "param.dev.frontend.SHIPPING_URL", value: "http://dev-shipping.bhakti-19.net:8080/"}
          - {name: "param.dev.frontend.PAYMENT_URL", value: "http://dev-payment.bhakti-19.net:8080/"}
          - {name: "param.dev.user.MONGO", value: "true"}
          - {name: "param.dev.user.MONGO_ENDPOINT", value: "http://dev-mongodb.bhakti-19.net"}
          - {name: "param.dev.user.MONGO_URL", value: "mongodb://dev-mongodb.bhakti-19.net:27017/users"}
          - {name: "param.dev.user.REDIS_HOST", value: "dev-redis.bhakti-19.net"}
          - {name: "param.dev.cart.REDIS_HOST", value: "dev-redis.bhakti-19.net"}
          - { name: "param.dev.cart.CATALOGUE_HOST", value: "dev-catalogue.bhakti-19.net" }
          - {name: "param.dev.cart.CATALOGUE_PORT", value: "8080"}
          - {name: "param.dev.mysql.ROOT_PASSWORD", value: "RoboShop@1"}
          - {name: "param.dev.shipping.DB_HOST", value: "dev-mysql.bhakti-19.net"}
          - {name: "param.dev.shipping.CART_ENDPOINT", value: "dev-cart.bhakti-19.net:8080"}
          - {name: "param.dev.shipping.ROOT_PASSWORD", value: "RoboShop@1"}
          - {name: "param.dev.payment.USER_HOST", value: "dev-user.bhakti-19.net"}
          - {name: "param.dev.payment.CART_HOST", value: "dev-cart.bhakti-19.net"}
          - {name: "param.dev.payment.AMQP_HOST", value: "dev-rabbitmq.bhakti-19.net"}
          - {name: "param.dev.payment.AMQP_USER", value: "roboshop"}
          - {name: "param.dev.payment.AMQP_PASS", value: "roboshop123"}
          - {name: "param.dev.rabbitmq.AMQP_PASS", value: "roboshop123"}
          - {name: "param.dev.rabbitmq.AMQP_USER", value: "roboshop"}





